INSERT INTO USER(EMAIL, PASSWORD) VALUES ('admin@admin.com', SHA2('secret', 256));
INSERT INTO ROLE(NAME) VALUES ('superuser');
INSERT INTO PERMISSION(NAME, DESCRIPTION) VALUES ('view.all', 'permission to everything');
INSERT INTO USER_ROLE(USER_ID, ROLE_ID) VALUES ((SELECT MAX(ID) FROM USER), (SELECT MAX(ID) FROM ROLE));
INSERT INTO ROLE_PERMISSION(PERMISSION_ID, ROLE_ID) VALUES ((SELECT MAX(ID) FROM PERMISSION), (SELECT MAX(ID) FROM ROLE));

INSERT INTO USER(EMAIL, PASSWORD) VALUES ('normal@normal.com', SHA2('secret', 256));
INSERT INTO ROLE(NAME) VALUES ('normal');
INSERT INTO PERMISSION(NAME, DESCRIPTION) VALUES ('view.create', 'permission to create');
INSERT INTO USER_ROLE(USER_ID, ROLE_ID) VALUES ((SELECT MAX(ID) FROM USER), (SELECT MAX(ID) FROM ROLE));
INSERT INTO ROLE_PERMISSION(PERMISSION_ID, ROLE_ID) VALUES ((SELECT MAX(ID) FROM PERMISSION), (SELECT MAX(ID) FROM ROLE));